# Generated by Django 6.0.4 on 2026-05-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField()),
                ('health_status', models.CharField(choices=[('excellent', 'Excellent 🌟'), ('good', 'Good ✅'), ('fair', 'Fair ⚠️'), ('poor', 'Poor ❌')], default='good', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='journal/')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Plant height in cm', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='gardens.gardenplot')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
