# Generated by Django 6.0.4 on 2026-05-03 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenBed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('width_ft', models.DecimalField(decimal_places=1, default=4.0, max_digits=5)),
                ('length_ft', models.DecimalField(decimal_places=1, default=8.0, max_digits=5)),
                ('soil_type', models.CharField(choices=[('loamy', 'Loamy'), ('sandy', 'Sandy'), ('clay', 'Clay'), ('silty', 'Silty'), ('peaty', 'Peaty'), ('chalky', 'Chalky'), ('mixed', 'Mixed / Raised Bed')], default='mixed', max_length=20)),
                ('light_condition', models.CharField(choices=[('full_sun', 'Full Sun'), ('partial_shade', 'Partial Shade'), ('full_shade', 'Full Shade')], default='full_sun', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_beds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GardenPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_planted', models.DateField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('planted', 'Planted'), ('sprouted', 'Sprouted'), ('growing', 'Growing'), ('flowering', 'Flowering'), ('ready', 'Ready to Harvest'), ('harvested', 'Harvested'), ('failed', 'Failed / Removed')], default='planted', max_length=20)),
                ('row', models.PositiveIntegerField(default=1)),
                ('col', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('harvest_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='gardens.gardenbed')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garden_plots', to='plants.plant')),
            ],
            options={
                'ordering': ['date_planted'],
            },
        ),
    ]
