# Generated by Django 6.0.4 on 2026-05-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('agri_officer', 'Agricultural Authority')], default='user', max_length=20),
        ),
    ]
