# Generated by Django 6.0.4 on 2026-05-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('vegetable', 'Vegetable'), ('herb', 'Herb'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('tree', 'Tree'), ('shrub', 'Shrub'), ('vine', 'Vine')], default='vegetable', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('sun_requirement', models.CharField(choices=[('full_sun', 'Full Sun (6+ hrs)'), ('partial_sun', 'Partial Sun (3-6 hrs)'), ('shade', 'Shade (< 3 hrs)')], default='full_sun', max_length=20)),
                ('water_frequency', models.CharField(choices=[('daily', 'Daily'), ('every_2_days', 'Every 2 Days'), ('twice_weekly', 'Twice a Week'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('days_to_germinate', models.PositiveIntegerField(default=7, help_text='Average days to germinate')),
                ('days_to_harvest', models.PositiveIntegerField(default=60, help_text='Average days from planting to harvest')),
                ('spacing_inches', models.PositiveIntegerField(default=12, help_text='Spacing between plants in inches')),
                ('companion_plants', models.CharField(blank=True, help_text='Comma-separated companion plant names', max_length=255)),
                ('avoid_plants', models.CharField(blank=True, help_text='Avoid planting near these', max_length=255)),
                ('planting_season', models.CharField(blank=True, help_text='e.g. Spring, Summer, Fall', max_length=100)),
                ('care_tips', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
