from django.core.management.base import BaseCommand
from plants.models import Plant

PLANTS_DATA = [
    # Vegetables
    {'name': 'Tomato', 'scientific_name': 'Solanum lycopersicum', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 75, 'spacing_inches': 24, 'companion_plants': 'Basil, Carrot, Marigold', 'avoid_plants': 'Fennel, Cabbage', 'planting_season': 'Spring, Summer', 'description': 'A versatile warm-season vegetable loved worldwide.', 'care_tips': 'Stake tall varieties. Remove suckers for better yield.'},
    {'name': 'Carrot', 'scientific_name': 'Daucus carota', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 14, 'days_to_harvest': 70, 'spacing_inches': 3, 'companion_plants': 'Tomato, Lettuce, Rosemary', 'avoid_plants': 'Dill', 'planting_season': 'Spring, Fall', 'description': 'Sweet root vegetable, great for cool seasons.', 'care_tips': 'Loosen soil deeply before planting. Thin seedlings to avoid forking.'},
    {'name': 'Lettuce', 'scientific_name': 'Lactuca sativa', 'category': 'vegetable', 'sun_requirement': 'partial_sun', 'water_frequency': 'daily', 'days_to_germinate': 7, 'days_to_harvest': 45, 'spacing_inches': 8, 'companion_plants': 'Carrot, Radish, Strawberry', 'avoid_plants': 'Celery', 'planting_season': 'Spring, Fall', 'description': 'Fast-growing leafy green, ideal for beginners.', 'care_tips': 'Harvest outer leaves first for continuous yield.'},
    {'name': 'Cucumber', 'scientific_name': 'Cucumis sativus', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'daily', 'days_to_germinate': 5, 'days_to_harvest': 55, 'spacing_inches': 36, 'companion_plants': 'Beans, Peas, Sunflower', 'avoid_plants': 'Potato, Sage', 'planting_season': 'Summer', 'description': 'Refreshing summer vegetable that loves heat.', 'care_tips': 'Trellis vines for better airflow and larger fruits.'},
    {'name': 'Bell Pepper', 'scientific_name': 'Capsicum annuum', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 14, 'days_to_harvest': 80, 'spacing_inches': 18, 'companion_plants': 'Basil, Tomato, Carrot', 'avoid_plants': 'Fennel', 'planting_season': 'Spring, Summer', 'description': 'Sweet pepper with colorful fruits.', 'care_tips': 'Start indoors 8-10 weeks before last frost.'},
    {'name': 'Spinach', 'scientific_name': 'Spinacia oleracea', 'category': 'vegetable', 'sun_requirement': 'partial_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 10, 'days_to_harvest': 40, 'spacing_inches': 6, 'companion_plants': 'Strawberry, Peas', 'avoid_plants': 'Potato', 'planting_season': 'Spring, Fall', 'description': 'Nutritious leafy green for cool weather.', 'care_tips': 'Bolt in heat. Grow in shade during summer.'},
    {'name': 'Onion', 'scientific_name': 'Allium cepa', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 10, 'days_to_harvest': 100, 'spacing_inches': 6, 'companion_plants': 'Carrot, Lettuce, Beet', 'avoid_plants': 'Peas, Beans', 'planting_season': 'Spring', 'description': 'Essential kitchen crop with long storage life.', 'care_tips': 'Reduce watering once tops begin to fall over.'},
    {'name': 'Radish', 'scientific_name': 'Raphanus sativus', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 4, 'days_to_harvest': 25, 'spacing_inches': 3, 'companion_plants': 'Carrot, Spinach, Cucumber', 'avoid_plants': 'Hyssop', 'planting_season': 'Spring, Fall', 'description': 'One of the fastest crops from seed to harvest.', 'care_tips': 'Direct sow every 2 weeks for continuous harvest.'},
    {'name': 'Zucchini', 'scientific_name': 'Cucurbita pepo', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 50, 'spacing_inches': 36, 'companion_plants': 'Nasturtium, Beans', 'avoid_plants': 'Potato', 'planting_season': 'Summer', 'description': 'Prolific summer squash, easy to grow.', 'care_tips': 'Harvest young (6-8 inches) for best flavor.'},
    {'name': 'Green Bean', 'scientific_name': 'Phaseolus vulgaris', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 8, 'days_to_harvest': 55, 'spacing_inches': 6, 'companion_plants': 'Carrot, Cucumber, Strawberry', 'avoid_plants': 'Onion, Fennel', 'planting_season': 'Spring, Summer', 'description': 'Easy to grow bush or pole bean.', 'care_tips': 'Pick frequently to encourage more pods.'},
    {'name': 'Broccoli', 'scientific_name': 'Brassica oleracea', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 80, 'spacing_inches': 18, 'companion_plants': 'Onion, Dill', 'avoid_plants': 'Tomato, Pepper', 'planting_season': 'Spring, Fall', 'description': 'Nutritious brassica, prefers cool weather.', 'care_tips': 'Harvest main head before flowers open.'},
    {'name': 'Eggplant', 'scientific_name': 'Solanum melongena', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 10, 'days_to_harvest': 75, 'spacing_inches': 24, 'companion_plants': 'Basil, Pepper', 'avoid_plants': 'Fennel', 'planting_season': 'Summer', 'description': 'Warm-season crop with glossy purple fruits.', 'care_tips': 'Needs warm soil; start indoors early.'},
    {'name': 'Pea', 'scientific_name': 'Pisum sativum', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 9, 'days_to_harvest': 60, 'spacing_inches': 4, 'companion_plants': 'Carrot, Radish, Turnip', 'avoid_plants': 'Onion, Garlic', 'planting_season': 'Spring, Fall', 'description': 'Cool season climber with sweet pods.', 'care_tips': 'Provide trellis support. Stop watering when pods fill.'},
    {'name': 'Garlic', 'scientific_name': 'Allium sativum', 'category': 'vegetable', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 14, 'days_to_harvest': 240, 'spacing_inches': 6, 'companion_plants': 'Tomato, Rose, Carrot', 'avoid_plants': 'Peas, Beans', 'planting_season': 'Fall', 'description': 'Planted in fall for summer harvest.', 'care_tips': 'Stop watering 2 weeks before harvest. Cure bulbs in shade.'},
    # Herbs
    {'name': 'Basil', 'scientific_name': 'Ocimum basilicum', 'category': 'herb', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 30, 'spacing_inches': 12, 'companion_plants': 'Tomato, Pepper', 'avoid_plants': 'Sage', 'planting_season': 'Summer', 'description': 'Aromatic herb, essential partner for tomatoes.', 'care_tips': 'Pinch flowers to keep producing leaves.'},
    {'name': 'Mint', 'scientific_name': 'Mentha spp.', 'category': 'herb', 'sun_requirement': 'partial_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 14, 'days_to_harvest': 90, 'spacing_inches': 18, 'companion_plants': 'Cabbage, Tomato', 'avoid_plants': 'Parsley', 'planting_season': 'Spring, Summer', 'description': 'Vigorous spreader. Best grown in containers.', 'care_tips': 'Contain roots to prevent invasive spreading.'},
    {'name': 'Rosemary', 'scientific_name': 'Salvia rosmarinus', 'category': 'herb', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 21, 'days_to_harvest': 90, 'spacing_inches': 24, 'companion_plants': 'Carrot, Cabbage, Beans', 'avoid_plants': 'Tomato', 'planting_season': 'Spring', 'description': 'Drought-tolerant Mediterranean herb.', 'care_tips': 'Avoid overwatering. Excellent on poor soils.'},
    {'name': 'Thyme', 'scientific_name': 'Thymus vulgaris', 'category': 'herb', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 14, 'days_to_harvest': 75, 'spacing_inches': 12, 'companion_plants': 'Cabbage, Tomato, Eggplant', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Hardy perennial herb with multiple culinary uses.', 'care_tips': 'Trim after flowering to promote bushy growth.'},
    {'name': 'Cilantro', 'scientific_name': 'Coriandrum sativum', 'category': 'herb', 'sun_requirement': 'partial_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 10, 'days_to_harvest': 45, 'spacing_inches': 6, 'companion_plants': 'Spinach, Basil', 'avoid_plants': 'Fennel', 'planting_season': 'Spring, Fall', 'description': 'Pungent herb used in many cuisines worldwide.', 'care_tips': 'Succession sow every 3 weeks. Bolts in heat.'},
    {'name': 'Parsley', 'scientific_name': 'Petroselinum crispum', 'category': 'herb', 'sun_requirement': 'partial_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 21, 'days_to_harvest': 75, 'spacing_inches': 8, 'companion_plants': 'Asparagus, Carrot, Tomato', 'avoid_plants': 'Mint', 'planting_season': 'Spring', 'description': 'Versatile biennial herb with bright flavor.', 'care_tips': 'Soak seeds overnight to speed germination.'},
    {'name': 'Dill', 'scientific_name': 'Anethum graveolens', 'category': 'herb', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 10, 'days_to_harvest': 60, 'spacing_inches': 12, 'companion_plants': 'Cabbage, Corn, Cucumber', 'avoid_plants': 'Carrot, Tomato', 'planting_season': 'Spring, Summer', 'description': 'Feathery herb, great for pickling.', 'care_tips': 'Direct sow; does not transplant well.'},
    {'name': 'Chives', 'scientific_name': 'Allium schoenoprasum', 'category': 'herb', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 14, 'days_to_harvest': 60, 'spacing_inches': 8, 'companion_plants': 'Carrot, Tomato, Parsley', 'avoid_plants': 'Peas, Beans', 'planting_season': 'Spring', 'description': 'Mild onion-flavored perennial herb.', 'care_tips': 'Clip to 2 inches above soil. Divide every 3 years.'},
    # Flowers
    {'name': 'Marigold', 'scientific_name': 'Tagetes spp.', 'category': 'flower', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 7, 'days_to_harvest': 45, 'spacing_inches': 10, 'companion_plants': 'Tomato, Pepper, Eggplant', 'avoid_plants': '', 'planting_season': 'Spring, Summer', 'description': 'Natural pest deterrent with vibrant orange blooms.', 'care_tips': 'Deadhead spent flowers for continuous blooming.'},
    {'name': 'Sunflower', 'scientific_name': 'Helianthus annuus', 'category': 'flower', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 7, 'days_to_harvest': 80, 'spacing_inches': 24, 'companion_plants': 'Cucumber, Corn', 'avoid_plants': 'Potato', 'planting_season': 'Spring, Summer', 'description': 'Tall, cheerful annual that attracts pollinators.', 'care_tips': 'Water deeply but infrequently. Great windbreak.'},
    {'name': 'Lavender', 'scientific_name': 'Lavandula angustifolia', 'category': 'flower', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 21, 'days_to_harvest': 90, 'spacing_inches': 24, 'companion_plants': 'Rose, Thyme, Sage', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Fragrant perennial beloved by bees.', 'care_tips': 'Excellent drainage essential. Do not overwater.'},
    {'name': 'Nasturtium', 'scientific_name': 'Tropaeolum majus', 'category': 'flower', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 10, 'days_to_harvest': 50, 'spacing_inches': 12, 'companion_plants': 'Cucumber, Zucchini, Cabbage', 'avoid_plants': '', 'planting_season': 'Spring, Summer', 'description': 'Edible flowers that repel aphids.', 'care_tips': 'Poor soil encourages more flowers than leaves.'},
    {'name': 'Zinnia', 'scientific_name': 'Zinnia elegans', 'category': 'flower', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 60, 'spacing_inches': 12, 'companion_plants': 'Tomato, Pepper', 'avoid_plants': '', 'planting_season': 'Summer', 'description': 'Bright colorful annual that attracts butterflies.', 'care_tips': 'Direct sow after last frost. Deadhead regularly.'},
    # Fruits
    {'name': 'Strawberry', 'scientific_name': 'Fragaria × ananassa', 'category': 'fruit', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 14, 'days_to_harvest': 90, 'spacing_inches': 12, 'companion_plants': 'Lettuce, Spinach, Borage', 'avoid_plants': 'Cabbage, Broccoli', 'planting_season': 'Spring', 'description': 'Sweet perennial berry for beds or containers.', 'care_tips': 'Remove runners to focus energy on fruit.'},
    {'name': 'Cherry Tomato', 'scientific_name': 'Solanum lycopersicum var. cerasiforme', 'category': 'fruit', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 7, 'days_to_harvest': 65, 'spacing_inches': 24, 'companion_plants': 'Basil, Parsley', 'avoid_plants': 'Fennel', 'planting_season': 'Spring, Summer', 'description': 'Prolific small tomatoes, perfect for snacking.', 'care_tips': 'Stake early. Consistent watering prevents blossom drop.'},
    {'name': 'Lemon', 'scientific_name': 'Citrus limon', 'category': 'fruit', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 30, 'days_to_harvest': 365, 'spacing_inches': 72, 'companion_plants': 'Lavender, Marigold', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Fragrant citrus tree for warm climates.', 'care_tips': 'Protect from frost. Feed with citrus fertilizer in spring.'},
    # Vines
    {'name': 'Passion Fruit', 'scientific_name': 'Passiflora edulis', 'category': 'vine', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 21, 'days_to_harvest': 365, 'spacing_inches': 120, 'companion_plants': 'Marigold', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Vigorous tropical vine with exotic fruits.', 'care_tips': 'Needs sturdy trellis. Frost-sensitive.'},
    {'name': 'Grape', 'scientific_name': 'Vitis vinifera', 'category': 'vine', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 0, 'days_to_harvest': 730, 'spacing_inches': 84, 'companion_plants': 'Basil, Rosemary', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Classic fruiting vine for arbors and trellises.', 'care_tips': 'Annual pruning is essential for good fruit production.'},
    # Shrubs
    {'name': 'Blueberry', 'scientific_name': 'Vaccinium corymbosum', 'category': 'shrub', 'sun_requirement': 'full_sun', 'water_frequency': 'every_2_days', 'days_to_germinate': 0, 'days_to_harvest': 730, 'spacing_inches': 60, 'companion_plants': 'Strawberry, Rhododendron', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Acidic soil lover with sweet berries.', 'care_tips': 'Plant at least 2 varieties for cross-pollination.'},
    {'name': 'Rosemary Bush', 'scientific_name': 'Salvia rosmarinus', 'category': 'shrub', 'sun_requirement': 'full_sun', 'water_frequency': 'weekly', 'days_to_germinate': 21, 'days_to_harvest': 180, 'spacing_inches': 36, 'companion_plants': 'Lavender, Sage', 'avoid_plants': '', 'planting_season': 'Spring', 'description': 'Large evergreen shrub form of rosemary.', 'care_tips': 'Prune after flowering to maintain shape.'},
]


class Command(BaseCommand):
    help = 'Seed the database with 50+ common garden plants'

    def handle(self, *args, **kwargs):
        created = 0
        skipped = 0
        for data in PLANTS_DATA:
            obj, was_created = Plant.objects.get_or_create(
                name=data['name'],
                defaults=data
            )
            if was_created:
                created += 1
            else:
                skipped += 1
        self.stdout.write(self.style.SUCCESS(
            f'✅ Seeding complete! Created: {created}, Already existed: {skipped}'
        ))
