# Generated by Django 6.0.4 on 2026-05-08 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Organic', 'Organic'), ('Chemical', 'Chemical'), ('Bio-fertilizer', 'Bio-fertilizer')], default='Organic', max_length=50)),
                ('quantity_available', models.CharField(help_text='e.g. 100 bags, 50 liters', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('usage_instructions', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(help_text='e.g. Vegetable, Fruit, Herb', max_length=50)),
                ('variety', models.CharField(blank=True, max_length=100)),
                ('quantity_available', models.CharField(help_text='e.g. 500 packets, 10 kg', max_length=50)),
                ('distribution_center', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FarmingTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farming_tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
