# Generated by Django 6.0.4 on 2026-05-03 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('water', 'Watering'), ('fertilize', 'Fertilizing'), ('prune', 'Pruning'), ('harvest', 'Harvesting'), ('pest_control', 'Pest Control'), ('weed', 'Weeding'), ('mulch', 'Mulching'), ('transplant', 'Transplanting')], max_length=20)),
                ('frequency_days', models.PositiveIntegerField(default=7, help_text='Repeat every N days')),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='gardens.gardenplot')),
            ],
            options={
                'ordering': ['next_due_date'],
            },
        ),
    ]
